server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      key-deserializer: "org.apache.kafka.common.serialization.IntegerDeserializer"
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      group-id: "kafka-consumer"
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"